using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sudoku
{
    public class PrintSudokuTemplate
    {
        public const string SUDOKUTEMPLATE = "<!DOCTYPE html>"
+ "<html lang=\"en\">"
+ "<head>"
+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" >"
+ "    <title>Have fun and solve with pleasure!</title>"
+ "    <style type=\"text/css\">"
+ "        body {"
+ "            font-family: Verdana;"
+ "            font-size: 40px;"
+ "        }"
+ "         #MainWindow {"
+ "         border: 4px solid black;"
+ "            margin: 0 auto;"
+ "            height: 423px;"
+ "            width: 423px;"
+ "            padding: 0 0 0 0;"
+ "        }"
+ "        .innerDivs {"
+ "            border: 3px solid black;"
+ "            padding: 0 0 0 0;"
+ "            margin: 0 0 0 0;"
+ "            height: 135px;"
+ "            width: 135px;"
+ "            float: left;"
+ "        }"
+ "        .numbersDivs {"
+ "            border: 2px solid black;"
+ "            padding: 0 0 0 0;"
+ "            margin: 0 0 0 0;"
+ "            height: 41px;"
+ "            width: 41px;"
+ "            float: left;"
+ "            text-align: center;"
+ "        }"
+ "    </style>"
+ "</head>"
+ "<body>"
+ "    <div id=\"MainWindow\" >"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox1\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox2\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox3\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox10\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox11\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox12\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox19\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox20\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox21\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox4\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox5\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox6\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox13\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox14\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox15\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox22\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox23\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox24\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox7\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox8\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox9\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox16\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox17\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox18\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox25\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox26\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox27\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox28\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox29\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox30\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox37\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox38\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox39\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox46\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox47\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox48\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox31\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox32\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox33\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox40\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox41\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox42\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox49\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox50\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox51\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox34\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox35\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox36\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox43\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox44\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox45\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox52\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox53\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox54\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox55\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox56\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox57\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox64\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox65\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox66\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox73\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox74\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox75\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox58\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox59\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox60\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox67\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox68\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox69\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox76\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox77\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox78\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox61\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox62\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox63\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox70\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox71\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox72\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox79\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox80\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox81\"></div>"
+ "        </div>"
+ "    </div>"
+ "    </br>"
+ "    <div id=\"MainWindow\" >"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox101\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox102\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox103\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox110\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox111\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox112\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox119\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox120\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox121\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox104\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox105\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox106\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox113\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox114\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox115\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox122\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox123\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox124\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox107\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox108\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox109\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox116\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox117\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox118\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox125\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox126\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox127\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox128\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox129\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox130\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox137\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox138\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox139\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox146\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox147\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox148\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox131\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox132\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox133\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox140\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox141\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox142\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox149\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox150\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox151\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox134\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox135\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox136\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox143\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox144\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox145\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox152\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox153\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox154\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox155\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox156\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox157\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox164\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox165\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox166\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox173\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox174\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox175\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox158\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox159\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox160\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox167\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox168\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox169\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox176\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox177\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox178\"></div>"
+ "        </div>"
+ "        <div class=\"innerDivs\">"
+ "            <div class=\"numbersDivs\" id=\"textBox161\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox162\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox163\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox170\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox171\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox172\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox179\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox180\"></div>"
+ "            <div class=\"numbersDivs\" id=\"textBox181\"></div>"
+ "        </div>"
+ "    </div>"
+ "</body>"
+ "</html>";
    }
}
